[package]
name = "koge29_h8-300h_emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7"
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "4.3.0", features = ["derive"] }
