[package]
name = "koge29_h8-3069f_emulator"
version = "0.1.1"
edition = "2021"

[dependencies]
nom = "7"
anyhow = { version = "1.0", features = ["backtrace"] }
clap = { version = "4.3.0", features = ["derive"] }
spin_sleep = "1.1.1"
