name: release
on:
  push:
    branches:
      - main
    paths:
      - Cargo.toml

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      is_new_version: ${{steps.check_version.outputs.previous-version != steps.check_version.outputs.current-version }}
      current_version: ${{steps.check_version.outputs.current-version}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check verson
        uses: salsify/action-detect-and-tag-new-version@v2
        id: check_version
        with:
          create-tag: false
          version-command: cargo read-manifest | jq -r .version


  build-windows:
    needs: check-version
    if: ${{needs.check-version.outputs.is_new_version}}
    runs-on: windows-latest
    steps:
      - name: Set rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build
        run: cargo build --release --target=x86_64-pc-windows-msvc

      - name: Package
        run: |
          powershell Compress-Archive -Path target/x86_64-pc-windows-msvc/release/koge29_h8-3069f_emulator.exe -DestinationPath h8-3069f_emulator-x86_64-pc-windows-msvc-${{needs.check-version.outputs.current_version}}.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: h8-3069f_emulator-x86_64-pc-windows-msvc-${{needs.check-version.outputs.current_version}}.zip
          path: ./h8-3069f_emulator-x86_64-pc-windows-msvc-${{needs.check-version.outputs.current_version}}.zip
          if-no-files-found: error

  build-linux:
    needs: check-version
    if: ${{needs.check-version.outputs.is_new_version}}
    runs-on: ubuntu-latest
    steps:
      - name: Install musl tools
        run: sudo apt install -qq -y musl-tools --no-install-recommends

      - name: Set rust-toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - name: Build
        run: cargo build --release --target=x86_64-unknown-linux-musl

      - name: Package
        run: |
          zip --junk-paths h8-3069f_emulator-x86_64-unknown-linux-musl-${{needs.check-version.outputs.current_version}}.zip target/x86_64-unknown-linux-musl/release/koge29_h8-3069f_emulator

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: h8-3069f_emulator-x86_64-unknown-linux-musl-${{needs.check-version.outputs.current_version}}.zip
          path: ./h8-3069f_emulator-x86_64-unknown-linux-musl-${{needs.check-version.outputs.current_version}}.zip
          if-no-files-found: error

  release:
    runs-on: ubuntu-22.04
    needs: [check-version, build-windows, build-linux]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts

      - name: Create tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          custom_tag: ${{needs.check-version.outputs.current_version}}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.create_tag.outputs.new_tag }}
          name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          artifacts:
            "./artifacts/h8-3069f_emulator-x86_64-pc-windows-msvc-${{needs.check-version.outputs.current_version}}.zip,
            ./artifacts/h8-3069f_emulator-x86_64-unknown-linux-musl-${{needs.check-version.outputs.current_version}}.zip"
          makeLatest: "latest"