name: run test
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  run-test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run test
        run: cargo test --all-features

      - name: notification
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
