name: run test
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  run-test:
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup rust-toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Run test
        run: cargo test --all-features

      - name: notification
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
